### ISSUE TITLE
Document best practices to make more sense of the data

### ISSUE THREAD

**Issue by hasan-dot** [liliana3186/sbv-world-health-org-metrics#10]
Since not all org members have the company set, also not all issues have proper categorization through labels for example so we might need to advice WHO in general to have some best practices in place in order to make sense of the data we have.

Example 1:
_**Concern:**_ Some users have their company as WHO others as World Health Organization
_**Explanation:**_ This might affect the metrics overall when we try to group contributes by company for example. Although we might be able to find common cases and map them, but that won't be feasible for all data.

Example 2:
_**Concern:**_ Not all issues are properly categorized using labels for example
_**Explanation:**_ This might affect the metrics overall when we try to find how many bugs, features, etc.; were implemented/fixed

**Comment by liliana3186** [comment]
https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/issues/16
