### ISSUE TITLE
Looking which sources we can use to get the information

### ISSUE THREAD

**Issue by darostegui** [liliana3186/sbv-world-health-org-metrics#6]
Looking to fill this table with possible sources of data 
Project: [World Health Org Metrics](https://github.com/users/liliana3186/projects/1)

|                  |         Repositories         |       Members      |              Projects             |    Labels (bugs)   |       Commits      | Discussions |   Users Snapshot   | [Contribution attribution](https://chaoss.community/kb/metric-contribution-attribution/) | [Organizational Diversity](https://chaoss.community/kb/metric-organizational-diversity/) | [Elephant Factor](https://chaoss.community/kb/metric-elephant-factor/) | [Project Awareness](https://chaoss.community/kb/metrics-model-project-awareness/) | [Project Velocity](https://chaoss.community/kb/metric-project-velocity/) | [License Coverage](https://chaoss.community/kb/metric-license-coverage/) |
|:----------------:|:----------------------------:|:------------------:|:---------------------------------:|:------------------:|:------------------:|:-------------:|:------------------:|:----------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------:|:----------------------------------------------------------------------:|:---------------------------------------------------------------------------------:|:------------------------------------------------------------------------:|:------------------------------------------------------------------------:|
|     REST API     | :heavy_check_mark:  (public) |         :x:        |                                   |                    |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
|      GRAPHQL     | :heavy_check_mark:  (public) |         :x:        |                                   |                    |                    |             |                    |                                                                                          |          :heavy_check_mark:  (Public)           |                                                                        |                                                                                   |                                                                          |                       :heavy_check_mark:  (public)                       |
| REST API (token) |      :heavy_check_mark:      |                    |                                   | :heavy_check_mark: |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                            :heavy_check_mark:                            |
|  GRAPHQL (token) |      :heavy_check_mark:      | :heavy_check_mark: | :heavy_check_mark: (classic + v2) | :heavy_check_mark: | :heavy_check_mark: | \:heavy_check_mark: |      ❓ Privacy     |                               :heavy_check_mark: :warning:                               |   \  :heavy_check_mark:    |                                                                        |                                                                                   |                                                                          |                            :heavy_check_mark:                            |
|    Stafftools    |      :heavy_check_mark:      | :heavy_check_mark: |         :heavy_check_mark:        |                    | :heavy_check_mark: |     :heavy_check_mark:        | :heavy_check_mark: |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
|   Datawarehouse  |      :heavy_check_mark:      |                    |                                   |                    |                    |             |                    |                                                                                          |                                                                                          |                                                                        |                                                                                   |                                                                          |                                                                          |
You can now import Markdown table code directly using File/Paste table data... dialog.

Comments:

**Users Snapshot:**
Considering the author of a Commit/PR/Comment - [Fields Available for User](https://docs.github.com/en/enterprise-cloud@latest/graphql/reference/objects#user)
 - [x] Country, 
 - [x] Region, 
 - [x] types of institutions, 
   - [x] company
   - [x] Sponsored
   - [x] Organization
   - [x] From Github
 - :x: status of implementation, 
 - :x: scope of implementation, 
 - :x: disease/use cases

:warning: There is something on this results that may not be complete or accurate

**Comment by liliana3186** [comment]
Issue https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/issues/10
